/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: e724a6495999e0e8a8ea386b11abca6f)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "Chat";
	}
	interface Env {
		Chat: DurableObjectNamespace<import("./src/server").Chat>;
		DB: D1Database;
		AI: Ai;
	}
}
interface Env extends Cloudflare.Env {}
